### ISSUE TITLE
error everytime on restart/stop

### ISSUE THREAD

**Issue by Legendmanj** [NikeyV1/DiscordSync#2]
```[17:17:11 ERROR]: [net.dv8tion.jda.internal.requests.Requester] There was an I/O error while executing a REST request: interrupted
[17:17:11 ERROR]: [net.dv8tion.jda.internal.requests.RateLimiter] Encountered exception trying to execute request
java.lang.IllegalStateException: zip file closed
        at java.base/java.util.zip.ZipFile.ensureOpen(ZipFile.java:846) ~[?:?]
        at java.base/java.util.zip.ZipFile.getEntry(ZipFile.java:338) ~[?:?]
        at java.base/java.util.jar.JarFile.getEntry(JarFile.java:516) ~[?:?]
        at java.base/java.util.jar.JarFile.getJarEntry(JarFile.java:471) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:209) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:593) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:169) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:164) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        at DiscordSyncSpigot.jar/net.dv8tion.jda.api.requests.Request.onFailure(Request.java:118) ~[DiscordSyncSpigot.jar:?]
        at DiscordSyncSpigot.jar/net.dv8tion.jda.internal.requests.RestActionImpl.handleResponse(RestActionImpl.java:270) ~[DiscordSyncSpigot.jar:?]
        at DiscordSyncSpigot.jar/net.dv8tion.jda.api.requests.Request.handleResponse(Request.java:259) ~[DiscordSyncSpigot.jar:?]
        at DiscordSyncSpigot.jar/net.dv8tion.jda.internal.requests.Requester.execute(Requester.java:253) ~[DiscordSyncSpigot.jar:?]
        at DiscordSyncSpigot.jar/net.dv8tion.jda.internal.requests.Requester.execute(Requester.java:140) ~[DiscordSyncSpigot.jar:?]
        at DiscordSyncSpigot.jar/net.dv8tion.jda.internal.requests.Requester.execute(Requester.java:123) ~[DiscordSyncSpigot.jar:?]
        at DiscordSyncSpigot.jar/net.dv8tion.jda.internal.requests.ratelimit.BotRateLimiter$Bucket.run(BotRateLimiter.java:478) ~[DiscordSyncSpigot.jar:?]
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572) ~[?:?]
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[?:?]
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]```
        please mind fixing this to make it so that the server stop message is available and is given by the bot rather than going offline without notice with error on console! 
        Thank-you

**Comment by NikeyV1** [comment]
I'm not at home right now and can't fix the bug for the next 1 1/2 weeks, but as soon as I'm back I'll take care of it

**Comment by Legendmanj** [comment]
> I'm not at home right now and can't fix the bug for the next 1 1/2 weeks, but as soon as I'm back I'll take care of it

thank you, take your time as it is not a very big issue as the plugin run as perfect as it is (;
ggs

**Comment by NikeyV1** [comment]
I fixed the message sending, but i sadly can't fix an error showing up on shutdown, because this has something to do with the message at the end
Update is soon on modrinth
